---
# Configure on RHEL7
- name: "set postgresql max_connections"
  lineinfile:
    dest=/var/lib/pgsql/data/postgresql.conf
    dest: /var/lib/pgsql/data/postgresql.conf
    line: max_connections = 400
    regexp: "^max_connections"
    state: present
  when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"

# Restart Satellite/Capsule
- name: "Services restarted"
  command:
    katello-service restart
...
