---
# Configure on RHEL7
- name: "set postgresql work_mem"
  lineinfile:
    dest=/var/lib/pgsql/data/postgresql.conf
    dest: /var/lib/pgsql/data/postgresql.conf
    line: work_mem = 4MB
    regexp: "^work_mem"
    state: present
  when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"

# Restart Satellite/Capsule
- name: "Services restarted"
  command:
    katello-service restart
...
