---
# Configure on RHEL7
- name: "RHEL7 httpd service directory created"
  file:
    path=/etc/systemd/system/qpidd.service.d
    state=directory
    owner=root
    group=root
    mode=0755
  when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"
- name: "RHEL7 qpidd limits.conf uploaded"
  copy:
    src=limits-qpidd.conf
    dest=/etc/systemd/system/qpidd.service.d/limits.conf
    owner=root
    group=root
    mode=0644
  when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"
- name: "RHEL7 qpidd service directory have correct SELinux context"
  command:
    restorecon -vR /etc/systemd/system/qpidd.service.d
  when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"
- name: "RHEL7 SystemD reloaded"
  command:
    systemctl daemon-reload
  when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"

# Restart katello servcies on Satellite/Capsule
- name: "Services restarted"
  command:
    katello-service restart
...
