---
# Configure on RHEL7
- name: "Tune passenger Globally"
  blockinfile:
    dest: /etc/httpd/conf.d/passenger.conf
    insertafter: PassengerRuby
    block: |
      PassengerMaxPoolSize 48
      PassengerMaxRequestQueueSize 400
      PassengerStatThrottleRate 120    
...
