---
# Configure on RHEL7
- name: "Tune Passenger Max Pool Size"
  lineinfile:
     dest: /etc/httpd/conf.d/passenger.conf
     insertafter: PassengerRuby
     regexp: "PassengerMaxPoolSize"
     line: "PassengerMaxPoolSize {{ ( ansible_processor_vcpus * PassengerMaxPoolSizeFactor )|round|int }}"
     state: present
- name: "Tune Passenger Max Request Queue Size"
  lineinfile:
     dest: /etc/httpd/conf.d/passenger.conf
     insertafter: PassengerRuby
     regexp: "PassengerMaxRequestQueueSize"
     line: "PassengerMaxRequestQueueSize {{ PassengerMaxRequestQueueSize }}"
     state: present
- name: "Tune Passenger Stat Throttle Rate"
  lineinfile:
     dest: /etc/httpd/conf.d/passenger.conf
     insertafter: PassengerRuby
     regexp: "PassengerStatThrottleRate"
     line: "PassengerStatThrottleRate {{ PassengerStatThrottleRate }}" 
     state: present
...
