---
# Configure on RHEL7
- name: "Tune Foreman Max Request Queue Size"
  lineinfile:
     dest: /etc/httpd/conf.d/05-foreman-ssl.conf
     regexp: "PassengerMaxRequestQueueSize"
     line: "PassengerMaxRequestQueueSize {{ PassengerForemanMaxRequestQueueSize  }}"
     state: present
- name: "Tune Passenger Stat Throttle Rate"
  lineinfile:
     dest: /etc/httpd/conf.d/05-foreman-ssl.conf
     regexp: "PassengerStatThrottleRate"
     line: "PassengerStateThrottleRate {{ PassengerForemanStatThrottleRate }}"
     state: present
- name: "Tune Passenger Foreman Min Instances"
  lineinfile:
     dest: /etc/httpd/conf.d/05-foreman-ssl.conf
     regexp: "PassengerMinInstances"
     lineinfile: "PassengerMinInstances {{ PassengerForemanMinInstances }}"
     state: present
...
