---
# Tune qpid memory
   - name: "Tune qpid session-max-unacked to reduce qpid memory consumption"
     lineinfile:
       dest: /etc/qpid/qpidd.conf
       line: "session-max-unacked={{ QpiddSessionMaxUnacked }}"
       regexp: "^session-max-unacked"
       state: present
...
