---
  #Setup postgres shared_buffers
  - name: "Set postgresql shared_buffers"
    lineinfile:
      dest: /var/lib/pgsql/data/postgresql.conf
      line: shared_buffers = 512MB
      regexp: "^shared_buffers"
      state: present
    #when: "ansible_distribution == 'Red Hat Enterprise Linux' and ansible_distribution_version == '7'"

  #Restart services for changes to take effect
  - name: "Restarting services for changes to take effect"
    command:
      katello-service restart
...
