---
- hosts: capsules
  vars_files:
    - ../conf/tunings.yaml
  remote_user: root
  roles:
    - pretune
    - smart_proxy_dynflow_core-max-open-files
    - smart_proxy_dynflow_core-change-sqlite-storage
    #- smart_proxy_dynflow_core-bz1416542c36
    - smart_proxy_dynflow_core-pool_size
    - common
