---
# Configure on RHEL7
- name: "Tune passenger for puppet Globally"
  blockinfile:
    dest: /etc/httpd/conf.d/25-puppet.conf
    insertafter: SSLOptions
    marker: "   #{mark} ANSIBLE MANAGED BLOCK"
    block: |4
      PassengerMinInstances 6
      PassengerStartTimeout 500
      PassengerMaxPreloaderIdleTime 0
      PassengerMaxRequests 10000
      PassengerPreStart https://satellite6.example.com:8140 
...
