---
# Configure on RHEL7
- name: "Tune qpid session-max-unacked"
  blockinfile:
    dest: /etc/qpid/qpidd.conf
    block: |
      session-max-unacked=100    
    insertafter: ssl-cert-name
  notify: bounce qpidd  
# Restart katello services on Satellite/Capsule
- name: "Services restarted"
  command:
    katello-service restart
...
